apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fibonacci
  name: fibb-loadbalancer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 11235
  selector:
    app: fibonacci
  type: LoadBalancer
status:
  loadBalancer: {}
