apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adapter
  name: adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adapter
    spec:
      volumes:
      - name: metric
        emptyDir: {}
      containers:
      - image: alpine:latest
        name: alpine
        volumeMounts:
        - name: metric
          mountPath : /metrics
        command: ["/bin/sh", "-c"]
        args:
        - mkdir /metrics;
          while true; do
            date > /metrics/raw.txt;
            top -n 1 -b >> /metrics/raw.txt;
            sleep 5;
          done
      - name: adapter
        image: httpd:latest
        volumeMounts:
        - name: metric
          mountPath : /metrics
        command: ["/bin/sh", "-c"]
        args:
        - while true; do
            date=$(head -1 /metrics/raw.txt);
            memory=$(head -2 /metrics/raw.txt | tail -1 | grep -o -E '\d+\w' | head -1);
            cpu=$(head -3 /metrics/raw.txt | tail -1 | grep -o -E '\d+%' | head -1);
            echo "{\"date\":\"$date\",\"memory\":\"$memory\",\"cpu\":\"$cpu\"}" > /metrics/adapted.json;
            sleep 5;
          done
status: {}
